FUTURES = {'GC': 'CHRIS/CME_GC1',
		   'CL': 'CHRIS/CME_CL1',
		   'NG': 'CHRIS/CME_NG1',
		   'ZC': 'CHRIS/CME_C1',
	       'ZS': 'CHRIS/CME_S1',
		   'ZL': 'CHRIS/CME_BO1',
		   'HO': 'CHRIS/ICE_O1',
		   '6E': 'CHRIS/CME_EC1',
		   '6C': 'CHRIS/CME_CD1',
	   	   '6A': 'CHRIS/CME_AD1',
           '6S': 'CHRIS/CME_SF1',
		   '6B': 'CHRIS/CME_BP1',
		   '6J': 'CHRIS/CME_JY1',
		   'ZN': 'CHRIS/CME_TY1',
		   'SB': 'CHRIS/ICE_SB1',
		   'KC': 'CHRIS/ICE_KC1',
		   'CC': 'CHRIS/ICE_CC1',
		   'ZW': 'CHRIS/CME_W1',
           'BC': 'BAVERAGE/USD',  #  BitCoin (Last)
           'FF': 'FRED/DFF',  # FED FUNDS Effective Rate (Value)
           'ES': 'CHRIS/CME_SP1',
           'DX': 'CHRIS/ICE_DX1',
           'PL': 'CHRIS/CME_PL1',
           'SI': 'CHRIS/CME_SI4',
           'RY': 'CHRIS/CME_RY1'
		   }
